# Deployment for multi-server (Express) pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: rallycoding/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service # name of the redis deployment's ClusterIP service
            - name: REDIS_PORT
              value: '6379' # redis default
            - name: PGUSER
              value: postgres # default
            - name: PGHOST
              value: postgres-cluster-ip-service # name of the postgres deployment's ClusterIP service
            - name: PGPORT
              value: '5432' # default
            - name: PGDATABASE
              value: postgres # default
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword # name of the secret object we set up
                  key: PGPASSWORD # name of key within secret